---
  name: Build, Test, and Deploy
  on:
    push:
      branches:
        - main
    pull_request:
      branches:
        - main
  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Set up Maven
          uses: actions/setup-java@v1
          with:
            java-version: "17"
        - name: Build with Maven (compile phase only)
          run: >
            cd GestorTareas/GestorTareasBackend/gestortareasbackend/gestortareasbackend
  
            mvn compile
            
            mvn clean package
        - name: deploy to azure
          uses: azure/webapps-deploy@v2
          with:
            app-name: 'GestorTareasCVDS'
            publish-profile: |
              <publishData>
                  <publishProfile profileName="GestorTareasCVDS - Web Deploy" publishMethod="MSDeploy"
                                  publishUrl="gestortareascvds-h8eghwareacbcchj.scm.eastus-01.azurewebsites.net:443"
                                  msdeploySite="GestorTareasCVDS" userName="REDACTED" userPWD="REDACTED"
                                  destinationAppUrl="https://gestortareascvds-h8eghwareacbcchj.eastus-01.azurewebsites.net"
                                  SQLServerDBConnectionString="REDACTED" mySQLDBConnectionString="" hostingProviderForumLink=""
                                  controlPanelLink="https://portal.azure.com" webSystem="WebSites">
                      <databases/>
                  </publishProfile>
              </publishData>
            package: $(pwd)/GestorTareas/GestorTareasBackend/gestortareasbackend/gestortareasbackend/target/gestortareasbackend-0.0.1-SNAPSHOT.jar
    test:
      needs: build
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Set up Maven
          uses: actions/setup-java@v1
          with:
            java-version: "17"
        - name: Run tests with Maven (verify phase)
          run: >
            cd GestorTareas/GestorTareasBackend/gestortareasbackend/gestortareasbackend
  
            mvn verify
    deploy:
      needs: test
      runs-on: ubuntu-latest
      steps:
        - name: Print deployment message
          run: echo "En construcción ..."
  